# mb.toml
#
# Configuration for MASTERMIND build
#
# (c) Andrew Shapton 2023, 2024
#


title = "MASTERMIND build Configuration TOML file"

[BuildParameters]
sourceFile      = "mm.asm"          # Source assembler file                             (Required)
assembledFile   = "mm.exe"          # Output assembled executable file                  (Required)
prefix          = "MM"              # Prefix for the blocks                             (Required)
base            = "0300"            # Base adress for origination/load of executable    (Required)
title           = "MASTERMIND"      # Title of program for Virtual Sphere               (Required)
vcass           = "mm"              # Filename for binary Virtual Sphere cassette V1      
vcass2          = "mm"              # Filename for binary Virtual Sphere cassette V2      
js              = "mm"              # Filename for Javascript Virtual Sphere cassette   
cassette        = "mm"              # Filename for .wav file for cassette audio         

# (Un)comment flags as required
flags           = [
                    "noheader",     # Don't generate a Javascript header for the Virtual Sphere
                    "movebin",      # Move the binary to the assets location post-build
                    "silent"        # Don't produce any output (except errors)
                    ]
[Locations]
convertEXEDir   = "/Users/andrew.shapton/MyProjects/sphere/HOMEBREW/TOOLS/CONVERT/"     # Location of convertEXE file
srcDir          = "/Users/andrew.shapton/MyProjects/sphere/HOMEBREW/GAME-MM/src/"       # Location of assembler source code
outputDir       = "/Users/andrew.shapton/MyProjects/sphere/HOMEBREW/GAME-MM/ASSETS/"    # Location of target assets

[Miscellaneous]
buildASM        = "build.asm"       # Name of build file (with version etc inside)
buildJustify    = "L"               # Justify property for build version -  C - Centre Justified [Default]
                                    #                                       L - Left Justified
                                    #                                       R - Right Justified
NLAfterBuildVersion = true          # true to place a new line after the build version [Default]
                                    # false for no new line
                                    # NOTE - MUST BE LOWER CASE


[Symbols]
symbolFile      = "src/SYMBOLS.SYM"     # A symbol file generated by the assembler 
                                        # MUST be specified correctly in the assembly code
defaultSymbols  = [                     # Symbols to include in debug list on startup
                   "START",
                   "CSRPTR",
                   ".RND"
                   ]

